move docker images to versioned repos in registry

diff --git a/bin/setupContainerFramework b/bin/setupContainerFramework
--- a/bin/setupContainerFramework
+++ b/bin/setupContainerFramework
@@ -5,13 +5,6 @@ set -o nounset
 set -o errexit
 
 ######################################################################
-function setupCBF.die()
-{
-    echo "***ERROR: $1" >&2
-    exit 1
-}
-
-######################################################################
 function setupCBF.createStructure()
 {
     local action_folders=${1:?"must pass parameter 'action_folders' to 'function ${FUNCNAME[0]}()'"}
@@ -55,6 +48,13 @@ function setupCBF.createStructure()
             mkdir -p "$subdir"
         done
     fi
+}
+
+######################################################################
+function setupCBF.die()
+{
+    echo "***ERROR: $1" >&2
+    exit 1
 }
 
 ######################################################################
