updates from dev branch for CBF v3.0
* updated to CBF v3.0
* fixes to docker-compose
* change term.bashlib to use property file instead of associative array
* change arg handling to report function name when requiremed arg not passed in
* move retrieval of CBF to build.sh and have it conditional
* use OS as package extension to indicate applicability
* ensure environments are correctly loaded loaded
* export all bashlib functions, and ensure bashlibs only get loaded once
* use bashlibs to provide UID/GID methods so we get default, enviroment var or 'getent'
* add "00.setup" action_folder
* use 'Unofficial BASH strict mode'
* implement checks for OS modules already loaded
* simplify package files: make extensions represent corresponding OS
* updated CRF

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -7,13 +7,15 @@
 
 set -o errexit
 set -o nounset
+set -o pipefail
+IFS=$'\t\n'
 
 declare -A test=()
 
 #############################################################################
 function test.installBatsModules()
 {
-    local -r test_dir=${1:?"must pass parameter 'test_dir' to 'function ${FUNCNAME[0]}()'"} 
+    local -ra test_dir=${1:?"must pass parameter 'test_dir' to 'function ${FUNCNAME[0]}()'"} 
     
     if [ ${#test[*]} -eq 0 ]; then
         # configure where our test framework comes from, adn in which dir it resides
@@ -25,9 +27,15 @@ function test.installBatsModules()
         git clone --depth 1 --recurse -q "${test['BATS_MODULES_REPO']}" "${test['BATS_DIR']}" > /dev/null 2>&1
 
         # load the framework
-        local -r dirs='bats-assert bats-support bats-file'
-        for dir in $dirs ; do
-            source "${test['BATS_DIR']}/${dir}/load.bash"
+        local -ra dirs=( bats-assert bats-support bats-file )
+        for dir in ${dirs[@]} ; do
+            local batFile="${test['BATS_DIR']}/${dir}/load.bash"
+            if [ -e "$batFile" ]; then
+                echo "Loading: '${batFile}'"
+                source "$batFile"
+            else
+                echo "Unable to load: '${batFile}'. No such file"
+            fi
         done
     fi
 }
